// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSM35ZkpJxrzs135O4yTVb1IsOiaddi4',
    appId: '1:146387819641:web:6820c729b4ff845a9588a8',
    messagingSenderId: '146387819641',
    projectId: 'spell-cards-fa177',
    authDomain: 'spell-cards-fa177.firebaseapp.com',
    databaseURL: 'https://spell-cards-fa177.firebaseio.com',
    storageBucket: 'spell-cards-fa177.appspot.com',
    measurementId: 'G-DNEHS92LNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxCQdyWqWr5fgdNKYEsOVAy2mx1zShXNA',
    appId: '1:146387819641:android:3277d6ead63937c39588a8',
    messagingSenderId: '146387819641',
    projectId: 'spell-cards-fa177',
    databaseURL: 'https://spell-cards-fa177.firebaseio.com',
    storageBucket: 'spell-cards-fa177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeMd355qwvrsPlgm7Y8s1VSJZ-TsjL1g',
    appId: '1:146387819641:ios:92709be098a49f139588a8',
    messagingSenderId: '146387819641',
    projectId: 'spell-cards-fa177',
    databaseURL: 'https://spell-cards-fa177.firebaseio.com',
    storageBucket: 'spell-cards-fa177.appspot.com',
    iosClientId: '146387819641-77i7qf4gg2ruusuqugmuicgnnoldu850.apps.googleusercontent.com',
    iosBundleId: 'com.example.dingo',
  );
}
